### ISSUE TITLE
Add other format text on the nameplate

### ISSUE THREAD

**Issue by Macumbafeh** [shagu/ShaguPlates#10]
Hey Shagu ! 
Just a suggestion for Shaguplates / PfUI Nameplates.
Actually it display HP text format with :
- Current HP / Max HP
- Percent
![image](https://user-images.githubusercontent.com/47739411/98436441-91254e80-20db-11eb-9bd7-ada8d05ffea5.png)
![image](https://user-images.githubusercontent.com/47739411/98436443-96829900-20db-11eb-9105-cf3dadb86223.png)

Is it possible to add those format also like ElvUI does : 
- Current HP (only)
- Current HP - Max HP | Percent
- Current HP - Percent
- Deficit
![image](https://user-images.githubusercontent.com/47739411/98436445-9c787a00-20db-11eb-8ff8-f3fca37f71d3.png)
![image](https://user-images.githubusercontent.com/47739411/98436446-9edad400-20db-11eb-9969-3359762c2010.png)
![image](https://user-images.githubusercontent.com/47739411/98436447-a306f180-20db-11eb-90d4-1bf6bcfd33bc.png)
![image](https://user-images.githubusercontent.com/47739411/98436448-a69a7880-20db-11eb-9c57-de9246af90b9.png)

And maybe to can put them on Right / left / Center.

Thanks

**Comment by shagu** [comment]
Thanks for your suggestion. Feature is available in 4.9.30 by the following commits: https://github.com/shagu/ShaguPlates/commit/378b9bd00c540a8b5e298292b927062543060f2b https://github.com/shagu/ShaguPlates/commit/34d7760f57e80dec0f751c53c4bcd297bcfd7782

![image](https://user-images.githubusercontent.com/11586807/103483247-2c8a2580-4de6-11eb-8d53-f17a7bd1aa44.png)

*(Upstream: https://github.com/shagu/pfUI/commit/2700f852833f850858b92997893f9efd77c19eb2 https://github.com/shagu/pfUI/commit/7780dfac21ac8d750fbbba37393088c7bfd7e7aa https://github.com/shagu/pfUI/commit/65a4defe363c3d7b2d19fa98c87fc5715277d483)*
