### ISSUE TITLE
REQUEST: Healthbar color based on enemy's target 

### ISSUE THREAD

**Issue by pbnme** [shagu/ShaguPlates#11]
Change the healthbar color of an enemy if you are not their target (for tanking purposes). Or... if you're able to incorporate threat values, change the enemy healthbar color to green when you lost aggro, yellow when threat is weak, and red when threat is strong. 

PS-thank you for your making these addons for the WoW community!

**Comment by shagu** [comment]
There's no Threat-API in Vanilla/TBC. It would require to write a combat log parser and some sort of threat-database holding every value for each attack (similar to KTM). This would be very inaccurate as it is based on Unit Names, that can be duplicates.

I don't see myself doing that, as the possible result would be not very useful.

**Comment by pbnme** [comment]
Would something simpler not based on threat values work, such as... if enemy has you as their target then healthbar is red, if enemy does not have you as their target then healthbar is green?

**Comment by shagu** [comment]
You can only check nameplates for their targets while having the nameplate in target or while hovering your mouse over it.
