### ISSUE TITLE
Counterspell

### ISSUE THREAD

**Issue by Energizer188** [shagu/ShaguPlates#14]
Hello !
There is a problem with the castbar below the nameplate : when we interrupt the spell the cast animation continue till the end, even though the cast has been correctly interrupted. 
I get this problem when I use Counterspell with my mage (and I'm playing on 1.12, Turtle WoW to be exact).
Hope this will be fixed, and thank you for all your work :)

**Comment by shagu** [comment]
Oh, Hello. Sorry I haven't seen this in my notifictions.

Much more of the interrupts should be fixed via: https://github.com/shagu/ShaguPlates/commit/d05666faa2e672ae9a4c7df8faab99a953c22f19

Without API modifications, this is the best I can do. ShaguPlates also supports SuperWoW which modifies the client to give addons a better API to work with. If SuperWoW is detected, you should always see 100% accurate castbars (even pushbacks).
