### ISSUE TITLE
Castbars are bugged

### ISSUE THREAD

**Issue by HuMa69** [shagu/ShaguPlates#17]
When an enemy is casting a spell if there are mobs with the same name it will show a castbar under every nameplate

**Comment by shagu** [comment]
It's not a bug. It can't be done better in vanilla.

There are no enemy castbars in 1.12.1 everything you see is guessed and based on the combat log which only provides a name. So whenever the combat log tells that XYZ is starting to cast something, it will add a castbar to every unit with that name.

There is no way to distinguish them based on combat log with the limitations of 1.12.1.
