### ISSUE TITLE
Setup Nameplate Offset in Options

### ISSUE THREAD

**Issue by Kirchlive** [shagu/ShaguPlates#21]
Dear Shagu,

the nameplates are displayed directly in the mobs and not above. 

Would be nice to have Y-Offset and X-Offset setting for the Nameplates itself in the Options. 
You always have to make the settings directly in the addon folder. Which is quite inconvenient.

Can you add these offset settings in the options please.

Best Regards!

**Comment by Kirchlive** [comment]
nameplates.lua
line 422
from nameplate:SetPoint("TOP", parent, "TOP", 0, 0)
to nameplate:SetPoint("TOP", parent, "TOP", 0, 35)

**Comment by SilverSaw** [comment]
i am doing this also manually, would be great if we have it in the options UI

**Comment by shagu** [comment]
Latest version has an option for it. :)
