### ISSUE TITLE
Castbars on enemies

### ISSUE THREAD

**Issue by Volkyte** [shagu/ShaguPlates#23]
when you attack an npc that is a caster, all mobs near him, even those not pulled and idle, show on their nameplate a castbar which does not correspond to the correct behaviour.

**Comment by shagu** [comment]
https://github.com/shagu/ShaguTweaks/issues/9
https://github.com/shagu/pfUI/issues/1254
https://github.com/shagu/pfUI/issues/1179
https://github.com/shagu/pfUI/issues/1129
https://github.com/shagu/ShaguPlates/issues/17
