### ISSUE TITLE
Own debuff highlights

### ISSUE THREAD

**Issue by urfinthejuce** [shagu/ShaguPlates#27]
When playing debuff-based class, warlock e.g., its very useful to know which mobs are already debuffed by your character. Can we have any highlights on their plates, e.g. size of icons?

**Comment by shagu** [comment]
No, the API call to determine if it is your own debuff was introduced during Wotlk, we don't have that in vanilla and tbc. All you can do is to use name based filter, but that would also show the named debuff if applied from another one.
