### ISSUE TITLE
Enemy unknown Tapping

### ISSUE THREAD

**Issue by SilverSaw** [shagu/ShaguPlates#32]
I am unable to understand if an enemy is tapped by another player on the nameplates. I am relying on nameplates and not unit frames. Often, I am finishing an already tapped mob. It would be great if the color turns gray on tapped mobs, like in most Unitframes add-ons.
![Capture](https://github.com/user-attachments/assets/5ff0cd29-816c-44e3-8a31-c6744afda574)

**Comment by shagu** [comment]
Nameplates in vanilla sadly can't do that. But with the recent version you will now see it when using the SuperWoW mod.
Fixed in: https://github.com/shagu/ShaguPlates/commit/ae9834da2c39272a859af8e6d90c82ecb04770bb

**Comment by SilverSaw** [comment]
@shagu  you are awesome, not even 24 hours since I dropped this suggestion. Thank you very much!
