### ISSUE TITLE
about castbar

### ISSUE THREAD

**Issue by Joshuagpt** [shagu/ShaguPlates#34]
-- castbar update
    if C.nameplates["showcastbar"] == "1" and ( C.nameplates["targetcastbar"] == "0" or target ) then
      local cast, nameSubtext, text, texture, startTime, endTime, isTradeSkill = UnitCastingInfo(target and "target" or name)

      if not cast then
        nameplate.castbar:Hide()
      **--elseif cast and (UnitIsPlayer(target and "target" or name) or UnitAffectingCombat(target and "target" or name)) then**
      elseif cast then
        local duration = endTime - startTime
        nameplate.castbar:SetMinMaxValues(0,  duration/1000)
        nameplate.castbar:SetValue(GetTime() - startTime/1000)
        nameplate.castbar.text:SetText(round(startTime/1000 + duration/1000 - GetTime(),1))
        if C.nameplates.spellname == "1" then
          nameplate.castbar.spell:SetText(cast)
        else
          nameplate.castbar.spell:SetText("")
        end
        nameplate.castbar:Show()

        if texture then
          nameplate.castbar.icon.tex:SetTexture(texture)
          nameplate.castbar.icon.tex:SetTexCoord(.1,.9,.1,.9)
        end
      end
    else
      nameplate.castbar:Hide()
    end
  end
----------------------------------------------------------------------------------------------->>>>>>>
First, I would like to express my gratitude for creating such an amazing addon. I'm currently encountering an issue in TurtleWoW: when there are numerous monsters with the same name on the screen, the cast bar displays that all of them are casting when just one monster uses a skill. I understand this is related to the API, making it difficult to determine which monster is actually casting. However, I need the cast bar to show only the monsters that have entered combat, as those not in combat should not be casting at all. Unfortunately, I am unable to achieve this because I cannot find the variable function that represents the monsters. Could you please assist me in optimizing this issue? I apologize for my poor English writing, and thank you!

**Comment by shagu** [comment]
That's not possible in vanilla as there is no nameplate API and also no enemy castbar API.
All castbars are guessed based on the combat log, which only tells a name, so it cannot differentiate between mobs with the same name. To have it working, you need a modified client (like SuperWoW) and it will be fine.

**Comment by Joshuagpt** [comment]
Thanks for the reply!
