### ISSUE TITLE
"Mouselook With Right Click" doesn't work

### ISSUE THREAD

**Issue by CrumpThePenguin** [shagu/ShaguPlates#35]
Apologies if I'm just misinterpreting what this setting is supposed to do. I would imagine it would allow you to still move your camera with right click even if your cursor is over a nameplate but that doesn't seem to be the case. It only does this with clickthrough enabled, but ideally I'd like to be able to have clickthrough off and mouselook on, so I can still mouse my camera with right click but be able to left click to target nameplates if needed.

Using 5.4.10 but I've had this problem for a few weeks now on 3 different computers and a lot of different addon setups. So while I cannot guarantee it I don't think it's likely that this is an addon conflict.

**Comment by shagu** [comment]
Hello, that's exactly what it is supposed to do. But it only works while the vertical offset is not touched (value: 0). That's one of the reasons why the vertical offset is marked as experimental. It's a weird workaround that makes quite some things not work as expected.

**Comment by CrumpThePenguin** [comment]
Ohhh my mistake! I was wondering why it was marked as experimental, maybe something mentioning that in the description would be a good idea if it's not planned to be fixed because of the difficulty. Thanks for responding!

**Comment by shagu** [comment]
No worries, it is planned to be fixed, but right now it's just in an experimental state :)

**Comment by shagu** [comment]
It should be fixed with the latest version via: https://github.com/shagu/ShaguPlates/commit/bf7bab4bd82c181b0bc9e540bf3d7727ecff6767

Could you please update and verify that everything now works as expected?

**Comment by CrumpThePenguin** [comment]
Wow, what a quick fix! It works great, exactly how I thought it would. Thanks so much!
