### ISSUE TITLE
debuffs: 2nd row of debuffs is aligned wrongly

### ISSUE THREAD

**Issue by Vitoshka** [shagu/ShaguPlates#5]
https://a.radikal.ru/a24/1804/45/6ab531dd0520.jpg

1) Can you make the display of the icons of buffs correct? 
2) Can you make the raid mark move so that it does not obstruct the text on the panel?

Thx for help

**Comment by shagu** [comment]
How should it look like?

**Comment by shagu** [comment]
I never had an issue with overlapping icons. Are you sure to not have any other nameplate or debuff addon active that causes this?

**Comment by Vitoshka** [comment]
I only use the Lunaframe and Bartender

**Comment by shagu** [comment]
Fixed: https://github.com/shagu/ShaguPlates/commit/1039cdf580f27f47d201fadc920206eca42ba508

Regarding the raidmarker, I'm not going to add an option for that.
