### ISSUE TITLE
Shaguplates for TBC

### ISSUE THREAD

**Issue by Macumbafeh** [shagu/ShaguPlates#8]
I wanna ask you if you can backport this awesome addon !
But someone did it for you : https://github.com/Anteara/HellfirePlates

It seems you just can change "Display HP on nameplate". The rest don't work... unfort.
And when you log out or /reload it reset ...

Do you wanna get an eye on it? :)

Many poeple are asking me for a fix for this addon !
You can find us in our TBC Addon discord : https://discord.gg/5qVu56M

Ty for them !

**Comment by Macumbafeh** [comment]
Look here the settings with /hp
https://ibb.co/H76bF1B
<a href="https://ibb.co/H76bF1B"><img src="https://i.ibb.co/H76bF1B/Hellfire-Plates.jpg" alt="Hellfire-Plates" border="0"></a>
https://i.ibb.co/H76bF1B/Hellfire-Plates.jpg
[url=https://ibb.co/H76bF1B][img]https://i.ibb.co/9n618zc/Hellfire-Plates.jpg[/img][/url]

**Comment by shagu** [comment]
ShaguPlates is now updated to the latest pfUI version and by that also supports TBC.

**Comment by Macumbafeh** [comment]
I just wanted use the nameplate Addon.
 Ty anyway.

**Comment by shagu** [comment]
?

That's why I updated the ShaguPlates addon.

**Comment by Macumbafeh** [comment]
Missunderstood thanks!
