### ISSUE TITLE
TBC: TotemPlates not working with ShaguPlates

### ISSUE THREAD

**Issue by aftab87** [shagu/ShaguPlates#9]
Is there a way to get TotemPlates working with ShaguPlates in TBC? No other nameplates I would use!
Thanks in advance!

**Comment by shagu** [comment]
> TotemPlates for 2.4.3 (hides totem nameplates) backport from http://sourceforge.net/projects/raiswotlkaddons/
According to the addon description, TotemPlates is only supposed to hide Totem nameplates. 

So i wonder what's wrong with this ShaguPlates option that makes you even want to use the addon:
![image](https://user-images.githubusercontent.com/11586807/96331715-e384c980-105f-11eb-864b-c0c37b34b7ca.png)

**Comment by aftab87** [comment]
Yes, I tried with the option on and off (I only see the totem's name if the option is on). ShaguePlates seems to override TotemPlate. Is there a way to make Shagu ignore totems altogether?

**Comment by aftab87** [comment]
How would I get the nameplate's name on line 174 in modules\nameplates.lua?

**Comment by shagu** [comment]
> Is there a way to make Shagu ignore totems altogether?

Not really, TotemPlates is so tightly coupled to the default nameplates, that it would be easier to add such an option to ShaguPlates than writing a compatibility layer to make TotemPlates work.

> How would I get the nameplate's name on line 174 in modules\nameplates.lua?

You don't want that. Nameplates are shared, what is now a totem, will be a unit later. So you can't simply ignore what is a totem "now" because after one camera turn, plate frames are different units.

I have played around with the support and this is where I stopped. Feel free to continue from there...
```diff
diff --git a/modules/nameplates.lua b/modules/nameplates.lua
index 805fcbe..dcb2e5a 100644
--- a/modules/nameplates.lua
+++ b/modules/nameplates.lua
@@ -487,7 +487,18 @@ ShaguPlates:RegisterModule("nameplates", "vanilla:tbc", function ()
     end
 
     -- hide frames according to the configuration
-    if HidePlate(unittype, name, (hpmax-hp == hpmin), target) then
+    local TotemPlates = plate.parent.totem and plate.parent.totem:IsShown() or nil
+
+    if TotemPlates then
+      -- Todo: realign the TotemTimer from stock plate to shagu's "plate" texture to make it visible
+      plate.parent.totem:SetParent(plate)
+      plate.parent.totem:SetPoint("CENTER", plate, "CENTER", 0, 0)
+
+      -- Todo: Hide all ShaguPlate elements
+      plate.level:Hide()
+      plate.name:Hide()
+      plate.health:Hide()
+    elseif HidePlate(unittype, name, (hpmax-hp == hpmin), target) or TotemPlates then
       plate.level:SetPoint("RIGHT", plate.name, "LEFT", -3, 0)
       plate.name:SetParent(plate)
       plate.health:Hide()
@@ -591,6 +602,7 @@ ShaguPlates:RegisterModule("nameplates", "vanilla:tbc", function ()
   nameplates.OnShow = function(frame)
     local frame = frame or this
     local nameplate = frame.nameplate
+    nameplate.parent = frame
 
     nameplates:OnDataChanged(nameplate)
   end
```

**Comment by aftab87** [comment]
Awesome! Thank you! I am new to LUA, but I have a feeling I know where to go with this.

**Comment by shagu** [comment]
The latest version of ShaguPlates now has an option to replace Totem-Nameplates with Icons. No additional addons required.
![image](https://user-images.githubusercontent.com/11586807/96335091-1934ad00-1076-11eb-90fc-38f8e8b6c551.png)

The Option is called "Replace Totems With Icons":
![image](https://user-images.githubusercontent.com/11586807/96335103-3bc6c600-1076-11eb-9aa6-03b2207a001e.png)

**Comment by aftab87** [comment]
Love it! Thanks a bunch! Will compare your code to mine. just missing the texture
